/**
 * Renders the torwache icons straight to PNG, no image libraries needed.
 * Shape: the dark arched-gate tile used by the website and extension UI.
 *
 *   node tools/make-icons.mjs
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'extension', 'public', 'icons');
const SIZES = [16, 32, 48, 128];
const SUPERSAMPLE = 4;
const DESIGN = {
  size: 64,
  tileInset: 0,
  tileRadius: 16,
  strokeWidth: 5,
  gate: {
    left: 14,
    right: 50,
    archY: 29,
    bottom: 49,
    archRadius: 18,
    crossbarLeft: 20,
    crossbarRight: 44,
    crossbarY: 35,
    centreX: 32,
  },
  colours: {
    tile: '#10312d',
    accent: '#2dd4bf',
  },
};

const TILE = rgb(DESIGN.colours.tile);
const ACCENT = rgb(DESIGN.colours.accent);

// --- geometry ---------------------------------------------------------------

/**
 * Signed distance to a rounded square centred on (0.5, 0.5).
 * @param {number} x @param {number} y @param {number} half @param {number} radius
 */
function roundedSquare(x, y, half, radius) {
  const dx = Math.abs(x - 0.5) - (half - radius);
  const dy = Math.abs(y - 0.5) - (half - radius);
  const outside = Math.hypot(Math.max(dx, 0), Math.max(dy, 0));
  return outside + Math.min(Math.max(dx, dy), 0) - radius;
}

/**
 * Distance to the line segment a->b.
 * @param {number} x @param {number} y
 * @param {number} ax @param {number} ay @param {number} bx @param {number} by
 */
function segment(x, y, ax, ay, bx, by) {
  const px = x - ax;
  const py = y - ay;
  const vx = bx - ax;
  const vy = by - ay;
  const t = Math.min(1, Math.max(0, (px * vx + py * vy) / (vx * vx + vy * vy)));
  return Math.hypot(px - vx * t, py - vy * t);
}

const STROKE = DESIGN.strokeWidth / 2 / DESIGN.size;
const ARCH_RADIUS = DESIGN.gate.archRadius / DESIGN.size;
const ARCH_Y = DESIGN.gate.archY / DESIGN.size;

/**
 * Distance to the arched gate: two posts joined by an upper semicircle.
 * @param {number} x @param {number} y
 */
function gateDistance(x, y) {
  const { archY, bottom, left, right } = DESIGN.gate;
  const leftPost = segment(
    x,
    y,
    left / DESIGN.size,
    archY / DESIGN.size,
    left / DESIGN.size,
    bottom / DESIGN.size,
  );
  const rightPost = segment(
    x,
    y,
    right / DESIGN.size,
    archY / DESIGN.size,
    right / DESIGN.size,
    bottom / DESIGN.size,
  );
  const arch = y <= ARCH_Y ? Math.abs(Math.hypot(x - 0.5, y - ARCH_Y) - ARCH_RADIUS) : 1;
  return Math.min(leftPost, rightPost, arch);
}

/**
 * Colour at a point in unit space, or null for transparent.
 * @param {number} x @param {number} y
 * @returns {readonly [number, number, number] | null}
 */
function shade(x, y) {
  const half = (DESIGN.size / 2 - DESIGN.tileInset) / DESIGN.size;
  if (roundedSquare(x, y, half, DESIGN.tileRadius / DESIGN.size) > 0) return null;

  const arch = gateDistance(x, y) <= STROKE;
  const { bottom, centreX, crossbarLeft, crossbarRight, crossbarY } = DESIGN.gate;
  const crossbar =
    segment(
      x,
      y,
      crossbarLeft / DESIGN.size,
      crossbarY / DESIGN.size,
      crossbarRight / DESIGN.size,
      crossbarY / DESIGN.size,
    ) <= STROKE;
  const centrePost =
    segment(
      x,
      y,
      centreX / DESIGN.size,
      crossbarY / DESIGN.size,
      centreX / DESIGN.size,
      bottom / DESIGN.size,
    ) <= STROKE;
  return arch || crossbar || centrePost ? ACCENT : TILE;
}

/** @param {string} hex @returns {readonly [number, number, number]} */
function rgb(hex) {
  return [
    Number.parseInt(hex.slice(1, 3), 16),
    Number.parseInt(hex.slice(3, 5), 16),
    Number.parseInt(hex.slice(5, 7), 16),
  ];
}

function renderSvg() {
  const { colours, gate, size, strokeWidth, tileInset, tileRadius } = DESIGN;
  const tileSize = size - tileInset * 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <!-- Generated by tools/make-icons.mjs. Edit the shared DESIGN there. -->
  <rect x="${tileInset}" y="${tileInset}" width="${tileSize}" height="${tileSize}" rx="${tileRadius}" fill="${colours.tile}" />
  <path d="M${gate.left} ${gate.bottom}V${gate.archY}a${gate.archRadius} ${gate.archRadius} 0 0 1 ${gate.archRadius * 2} 0v${gate.bottom - gate.archY}" fill="none" stroke="${colours.accent}" stroke-linecap="round" stroke-linejoin="round" stroke-width="${strokeWidth}" />
  <path d="M${gate.crossbarLeft} ${gate.crossbarY}h${gate.crossbarRight - gate.crossbarLeft}M${gate.centreX} ${gate.crossbarY}v${gate.bottom - gate.crossbarY}" fill="none" stroke="${colours.accent}" stroke-linecap="round" stroke-width="${strokeWidth}" />
</svg>
`;
}

/**
 * Box-filtered render: supersample, then average in premultiplied space.
 * @param {number} size
 * @returns {Buffer}
 */
function render(size) {
  const pixels = Buffer.alloc(size * size * 4);
  const step = 1 / (size * SUPERSAMPLE);
  const samples = SUPERSAMPLE * SUPERSAMPLE;

  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let hits = 0;

      for (let sy = 0; sy < SUPERSAMPLE; sy++) {
        for (let sx = 0; sx < SUPERSAMPLE; sx++) {
          const colour = shade(
            (px * SUPERSAMPLE + sx + 0.5) * step,
            (py * SUPERSAMPLE + sy + 0.5) * step,
          );
          if (!colour) continue;
          r += colour[0];
          g += colour[1];
          b += colour[2];
          hits++;
        }
      }

      const at = (py * size + px) * 4;
      if (!hits) continue;
      pixels[at] = Math.round(r / hits);
      pixels[at + 1] = Math.round(g / hits);
      pixels[at + 2] = Math.round(b / hits);
      pixels[at + 3] = Math.round((hits / samples) * 255);
    }
  }
  return pixels;
}

// --- PNG container ----------------------------------------------------------

const CRC_TABLE = Int32Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c;
});

/** @param {Buffer} buf */
function crc32(buf) {
  let c = -1;
  for (const byte of buf) c = (CRC_TABLE[(c ^ byte) & 0xff] ?? 0) ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

/** @param {string} type @param {Buffer} data */
function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

/** @param {number} size @param {Buffer} pixels @returns {Buffer} */
function encodePNG(size, pixels) {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // truecolour with alpha

  const stride = size * 4;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (stride + 1)] = 0; // filter: none
    pixels.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// --- go ---------------------------------------------------------------------

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'mark.svg'), renderSvg());
console.log('mark.svg');
for (const size of SIZES) {
  const file = join(OUT, `icon${size}.png`);
  writeFileSync(file, encodePNG(size, render(size)));
  console.log(`icon${size}.png`);
}
